version: 2

before:
  hooks:
    - go install github.com/akavel/rsrc@latest
    - rsrc -ico icon.ico -manifest main.manifest -o rsrc.syso

builds:
  - goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -H windowsgui
    flags:
      - -trimpath

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Version }}_windows_amd64"

release:
  github:
    owner: BananaJeanss
    name: gta-nosave-go
