version: "3"

tasks:
  build:
    silent: true
    cmds:
      - rsrc -ico icon.ico -manifest main.manifest -o rsrc.syso
      - go build -ldflags="-H windowsgui" -o gta-nosave.exe .
  runAsAdmin:
    silent: true
    cmds:
      - powershell -Command "Start-Process 'gta-nosave.exe' -Verb runAs"
